dist: trusty

language:
  - c++

compiler:
  - gcc-5.4

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8

before_install:
  - pwd
  - echo $PATH

script:
  - g++ -std=c++11 -O3 test_data.cpp -o test_data
  - cd src && make -j8 blinktree_single_thread blinktree_with_queue blinktree_multi_thread \
  lsmtree_single_thread lsmtree_with_queue lsmtree_multi_thread

notifications:
  email:
    on_success: always
    on_failure: never
    on_error: never
