language: cpp

compiler:
  - g++

sudo: required

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5.4 CC=gcc-5.4
      addons:
        apt:
          packages:
            - gcc-5.4
            - g++-5.4
          sources: &sources
            - ubuntu-toolchain-r-test
script:
  - cd src
  - make all

notifications:
  email:
    on_success: always
    on_failure: never
    on_error: never
