
# language:
#   - c++

# compiler:
#   - gcc-5.4

# matrix:
#   include:
#     - os: linux
#     - os: osx
#       osx_image: xcode8

# before_install:
#   - pwd
#   - echo $PATH

dist: trusty

language: cpp

compiler:
  - g++

matrix:
  include:
    - os: linux

script:
  - g++ -std=c++11 -O3 test_data.cpp -o test_data
  - cd src && make -j8 lsmtree_with_queue

notifications:
  email:
    on_success: always
    on_failure: never
    on_error: never
